version: '3'
services:
  server:
    networks:
      network:
    build:
      context: ./server
    ports:
      - 3080:3080
    container_name: server
    volumes:
      - ./server:/server
      - /server/node_modules
  api:
    networks:
      network:
    build:
      context: ./api
    ports:
      - 3100:3100
    container_name: api
    volumes:
      - ./api:/api
      - /api/node_modules
  frontend:
    networks:
      network:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    container_name: frontend
    depends_on:
      - server
      - api
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      WATCHPACK_POLLING: true
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: wp_pkim_db
  mysql:
    networks:
      network:
    build:
      context: ./db
    ports:
      - 3010:3010
    volumes:
      -  mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wp_pkim_db
  phpmyadmin:
    networks:
      network:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wp_pkim_db

volumes:
  mysql-data:

networks:
  network:
    driver: bridge